server:
    port: 8988
spring:
    application:
        name: service-hi
    profiles:
          active: node2
    sleuth:
        sampler:
            percentage: 1
    zipkin:
        base-url: http://${spring.profiles.active}:9411
